name: create-docs

on:
  push:
    branches:
    - master

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e
        
    - name: Creating the docs
      run: |
        pdoc --logo https://i.ibb.co/NstG5hz/03.png -o html_docs dlc2action

    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.9.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html_docs
